version: '3'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
    ### API #######################################################
    api:
      build: ./api
      volumes:
        - ${APP_ROOT_PATH}:${DOCKER_APP_ROOT_PATH}
      ports:
        - "${APP_SERVICE_PORT}:${APP_SERVICE_PORT}"
      depends_on:
        - postgres
      networks:
        - backend

    ### PostgreSQL ################################################
    postgres:
      build: ./postgres
      volumes:
        - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
        - ${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${POSTGRES_PORT}:5432"
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      networks:
        - backend

    ### Nginx ######################################################
    nginx:
      build: ./nginx
      volumes:
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
      depends_on:
        - api
      networks:
        - backend
